### PR TITLE
June Meeting revisions

### PR DESCRIPTION
**Pull request by elstamey**
I mislabeled the branch name just now.  :(

### CODE REVIEW

**Comment by cmgmyr** [comment]
@elstamey did you mean to make a copy of the April file, or the template file?

**Comment by elstamey** [comment]
Yeah, it was the last one.  Mostly I needed to get those conference discount codes down.  I can copy them somewhere else later.

**Comment by flashadvocate** [comment]
@cmgmyr @elstamey can you resolve this so I can pull the latest version down :)

**Comment by cmgmyr** [comment]
@flashadvocate This is the same as 2018/04.md, just the php conferences are different - but I don't think they are valid anymore. I'm just going to close this for now.

(04 on left, 06 on right)
screen shot 2018-08-15 at 4 29 39 pm

**Pull request closed without merging**
