### PR TITLE
May meeting

### PR DESCRIPTION
**Pull request by elstamey**
I'm working on the details of php updates.  If you know of something you want to add, just make a comment here.  I'll need info on how you were building this to display.

### CODE REVIEW

**Comment by cmgmyr** [comment]
@elstamey looks great! Just a few quick things:

1. It doesn't look like GH is connecting your commits to your account. Looks like you're using your work email, so that's probably why
2. PHP Storm had a minor release yesterday - https://blog.jetbrains.com/phpstorm/ and might want to mention the EAP for 2017.2 (optional)
3. What do you think about adding the "Have a job, need a job" as the last slide after the one for next month's meeting? Figured it would be a good segway and that we wouldn't forget to do it :)

**Comment by elstamey** [comment]
Thanks, Chris!  This was something I hadn't actually handled correctly in my last position, and I found a graceful way to hand repos individually and a script to correct mislabeld authors in personal repos.  :)

I added the have a job/need a job and will do the PHP Storm.  I could not find that in my searches.  We should probably bookmark the places that best show these release notes to save time.

**Comment by cmgmyr** [comment]
huh, I thought I had included links in the template...I guess not. Once you're finished up with this new file, can you update the template with the new sections/links?

**Comment by elstamey** [comment]
OK.  This is where things went awry.  I missed the template.  I've been googling them manually.  I have questions about the TOC too, so I'll ping you on slack.  :)

**Pull request merged**
